version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/robot_trader" # Updated path
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/robot_trader/server" # Updated path
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/server" # Verified path
    schedule:
      interval: "weekly"
